name:    Test workflow
on:
    push:
        branches: [main]
jobs:
    test_job:
        name: Executando o Job Teste
        runs-on: self-hosted
        steps:
        - name: Step 1
        uses: actions/checkout@v2
        
         
       
