name: Test workflow

on:
  push:
    branches: 
      - main

jobs:
  test_job:
    name: Executando o Job Teste
    runs-on: ubuntu-latest  # Corrigido para 'ubuntu-latest'
    steps:
      - name: Step 1
        uses: actions/checkout@v3
      - name: Docker Login 
        uses: docker/login-action@v3
        with:      
          username: 'ciroa'
          password: ${{ secrets.TESTE_GITHUB }}
      - name: Build and push Docker images 
        uses: docker/build-push-action@v6.7.0
        with:
            context: .
            tags: 'ciroa/testefiap:latest'
            push: true
